version: '3'
services:
  localdb:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    env_file:
      - .env.local
  # frontend:
  #   image: localhotturbo:frontend
  #   build:
  #     context: ./frontend
  #     args:
  #       - VITE_APP_ENV=${VITE_APP_ENV}
  #       - VITE_API_BASE_URL=${VITE_API_BASE_URL}
  #       - VITE_API_V1_PREFIX=${VITE_API_V1_PREFIX}
  #   ports:
  #     - 3000:80
  #   env_file:
  #     - .env.local
  # backend:
  #   image: localhotturbo:backend
  #   build:
  #     context: ./backend
  #   depends_on:
  #     - localdb
  #   command: >
  #     /bin/ash -c "uvicorn app.main:app --port 8000 --host 0.0.0.0"
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env.local
